name: Auto Version Update

# Workflow'u tetikleyen olaylar
on:
  push:
    branches:
      - master  # Ana branch'e yapılan her push işleminde çalışacak
    paths:
      - version.txt  # Yalnızca version.txt dosyasındaki değişiklikleri dinliyoruz

jobs:
  version-update:
    runs-on: ubuntu-latest  # GitHub Actions işlemi Ubuntu üzerinde çalışacak

    steps:
      # 1. Kodu çekiyoruz
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Git konfigürasyonunu yapıyoruz (E-posta ve kullanıcı adı)
      - name: Set up Git configuration
        run: |
          git config --global user.email "muradofftehmez01@gmail.com"
          git config --global user.name "MuradoffTehmez"

      # 3. Versiyon numarasını güncelliyoruz
      - name: Update version number
        run: |
          VERSION_FILE="version.txt"
          
          # version.txt dosyasındaki mevcut versiyon numarasını oku
          VERSION=$(cat $VERSION_FILE)
          
          # Versiyon numarasını ayır
          IFS='.' read -r major minor patch <<< "$VERSION"
          
          # Patch numarasını 1 artır
          patch=$((patch + 1))
          
          # Yeni versiyon numarasını oluştur
          NEW_VERSION="$major.$minor.$patch"
          
          # Yeni versiyonu version.txt dosyasına yaz
          echo $NEW_VERSION > $VERSION_FILE

      # 4. Değişiklikleri commit ediyoruz
      - name: Commit changes
        run: |
          # Git'e değişiklikleri ekliyoruz
          git add $VERSION_FILE
          
          # Commit mesajı oluşturuyoruz
          COMMIT_MSG="Auto version update to $NEW_VERSION"
          
          # Değişiklikleri commit ediyoruz
          git commit -m "$COMMIT_MSG" || echo "No changes to commit"

      # 5. Değişiklikleri GitHub'a push ediyoruz
      - name: Push changes
        run: |
          git remote set-url origin https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/MuradoffTehmez/cafe_restoran_app.git
          git push origin master
